/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANDREW
 */
public class interCarrito extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    static ArrayList<Factura> list = new ArrayList<>();
    public static DefaultTableModel modelo;
    FondoMarcas fondo = new FondoMarcas();
    Registro registro = new Registro();
    Compra comprar = new Compra();
    Producto pr;
    Factura f;
    String aux;
    static int op;
    public interCarrito() {
        this.setContentPane(fondo);
        initComponents();
        modelo = (DefaultTableModel) Tabla2.getModel();
        setLocationRelativeTo(null);
        backgrounds();
        listaCarrito();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoMarcas();
        title2 = new javax.swing.JLabel();
        suCompra = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla2 = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        seguirCompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title2.setBackground(new java.awt.Color(255, 0, 0));
        title2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        title2.setForeground(new java.awt.Color(255, 255, 255));
        title2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2.setText("Carrito");
        title2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        suCompra.setBackground(new java.awt.Color(255, 0, 0));
        suCompra.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        suCompra.setForeground(new java.awt.Color(255, 255, 255));
        suCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suCompra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MARCA", "TIPO", "ID", "VALOR", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla2.setRowHeight(30);
        Tabla2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla2);

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnComprar.setBackground(new java.awt.Color(0, 204, 0));
        btnComprar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        seguirCompra.setText("Seguir comprando");
        seguirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguirCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(seguirCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(suCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seguirCompra))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnComprar)
                        .addComponent(btnCancelar)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tabla2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla2MouseClicked
        // TODO add your handling code here:
        int selection =  Tabla2.rowAtPoint(evt.getPoint());
        int op = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el producto del carrito?");
        if(op == 0){
            list.remove(selection);
            listaCarrito();
        }
        
    }//GEN-LAST:event_Tabla2MouseClicked

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        double cnt = 0;
        for(int i = 0; i < list.size(); i++){
            cnt += list.get(i).getP().getPrecio();
        }
        this.dispose();
        new interCompra().setVisible(true);
        interCompra.title4.setText(" Total a pagar $"+cnt);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void seguirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguirCompraActionPerformed
        // TODO add your handling code here:
        if(list.isEmpty()){
            this.dispose();
            new interCliente().setVisible(true);
            interCliente.iniSesion.setVisible(false);
            interCliente.cerrar.setVisible(true);
            interCliente.hola.setVisible(true);
            interCliente.user.setText(aux);
            interCliente.chart.setVisible(false);
        }else{
            this.dispose();
            new interCliente().setVisible(true);
            interCliente.iniSesion.setVisible(false);
            interCliente.cerrar.setVisible(true);
            interCliente.hola.setVisible(true);
            interCliente.user.setText(aux);
            interCliente.chart.setVisible(true);
        }
    }//GEN-LAST:event_seguirCompraActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if(list.isEmpty()){
            this.dispose();
            new interCliente().setVisible(true);
            interCliente.iniSesion.setVisible(false);
            interCliente.cerrar.setVisible(true);
            interCliente.hola.setVisible(true);
            interCliente.user.setText(aux);
            interCliente.chart.setVisible(false);
        }else{
        int op = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cancelar la compra?");
            if(op == 0){
                list.removeAll(list);
                this.dispose();
                new interCliente().setVisible(true);
                interCliente.iniSesion.setVisible(false);
                interCliente.cerrar.setVisible(true);
                interCliente.hola.setVisible(true);
                interCliente.user.setText(aux);
                interCliente.chart.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed
    public void backgrounds(){
        title2.setOpaque(true);
        suCompra.setOpaque(true);
    }
    
    public void listaCarrito(){
        int j = 0;
        if(modelo.getRowCount() != 0){
            while(j != -1){
                try{
                    modelo.removeRow(modelo.getRowCount() - 1);
                }catch(Exception e){
                    j = -1;
                }
            }
        }
        try{
            for(int i = 0; i < list.size(); i++){
  
                String marca =  list.get(i).getP().getMarca();
                String tipo = list.get(i).getP().getNombre();
                String ID = list.get(i).getP().getID();
                String valor = String.valueOf(list.get(i).getP().getPrecio());
                String cantidad = String.valueOf(list.get(i).getP().getCantidad());
                this.aux = interCliente.user.getText();
                String [] obj = {marca, tipo, ID, valor, cantidad};

                modelo.addRow(obj);
        }
        }catch(Exception e){
            System.out.println("Error: "+ e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interCarrito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabla2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton seguirCompra;
    public static javax.swing.JLabel suCompra;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
    class FondoMarcas extends JPanel{
        private Image imagen;
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/img/marcas.jpg")).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            
            super.paint(g);
            
        }
    }
}
